---
- name: Configure standard ACL
  hosts: R1
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: Load new ACL into device
     ios_config:
       parents: ip access-list extended REQ3
       lines:
         - permit tcp host 192.168.20.20 host 192.168.10.10 eq www
         - deny tcp any any eq www
         - permit ip any any

   - name: Apply new ACL to R1 Eth0/1 out
     ios_config:
       parents: int e0/0.10
       lines:
         - ip access-group REQ3 out

   - name: Check result
     ios_command:
       commands: sh run | begin line vty 0 4
     register: result

   - name: Print result
     ios_command:
       commands: sh ip access-lists REQ3
     register: output
